### ISSUE TITLE
Remove Mashape dependency

### ISSUE THREAD

**Issue by Insti** [justuswilhelm/beemodoro#2]
Is there a reason why you call the Beeminder API via Mashape rather than just calling the Beeminder API directly?

**Comment by justuswilhelm** [comment]
I have been using Mashape mainly out of convenience and laziness. It would make the application a lot easier to use if it called Beeminder directly. I will fix that by tomorrow.
Thanks for filing two issues, I appreciate your input :)

**Comment by justuswilhelm** [comment]
OK, 859af61657d56ce16d7b4e6f8e7fd7ad16a30a3c should fix this. You can install the newest version via `pip`:

```
pip3 install beemodoro==1.2.0 --upgrade
```
